Staging 2022 sept
ErlenePsyD/ssgweb pull request #12
Opened 2022-09-27 14:10 UTC by flexicon33

New blog post on curiosity.

2022-09-27 16:35 UTC, stratofax requested changes
I suggested some changes in the Markdown file. Also, don't include `poetry.lock` files in content commits -- that's really a configuration change, and we should try to avoid arbitrary changes to poetry versions if possible.

2022-09-27 16:35 UTC, stratofax commented on erlenepsyd.com/content/blog/focus-on-curiosity.md
> +![Boy filled with wonder]({static}/images/kyle-nieber-f0tKahz0DVA-unsplash.jpg){: .image-process-crisp}
Great pick for the image! I'd suggest being a little more descriptive for the alt tag, like this:

```
![A toddler boy gazes up into the forest with curiosity]...
```

Note the use of the "curiosity" keyword in the alt tag.

2022-09-27 16:35 UTC, stratofax commented on erlenepsyd.com/content/blog/focus-on-curiosity.md
> +Focus on: CURIOSITY
This is redundant and I think this line should be removed.

2022-09-27 16:35 UTC, stratofax commented on erlenepsyd.com/content/blog/focus-on-curiosity.md
> +How is curiosity diminished?
I'd make this an L2 heading, like this:

```
## How is curiosity diminished?
```

2022-09-27 16:35 UTC, stratofax commented on erlenepsyd.com/content/blog/focus-on-curiosity.md
> +A lot of time it is diminished by what we tell ourselves. Especially those recurring negatives and self-defeating 'over and over' ones. Some examples of things we tell ourselves: "What difference wou
This paragraph is too long and should be broken up as follows:

- The first two sentences should be combined into one (replace the first period with a comma) as the second sentence, starting with "Especially," is incomplete.
- The sentence starting with "Some examples..." should be a new paragraph.
- Each of the quotes after the colon should be a separate bullet item in a bullet list.
- The final sentence after the quotes should be a new paragraph.

2022-09-27 16:35 UTC, stratofax commented on erlenepsyd.com/content/blog/focus-on-curiosity.md
> +"That's kind of different/neat/cool. I wonder..." "I have no idea how/about (something). I'm going to look it up." "The newspaper was reviewing a show at the (theatre/cinema/museum/etc.) I haven't be
Again, please separate these individual quotes into a bullet list.

2022-09-27 16:35 UTC, stratofax commented on erlenepsyd.com/content/blog/focus-on-curiosity.md
> +There is a wonderful Buddhist proverb that states: "When the student is ready, the teacher will appear." Of course, a real flesh and blood teacher does not appear in response to our curiosity. Rather
This looks like a conversion artifact:

```
**willingness** **to be open**
```

should be:

```
**willingness to be open**
```

2022-09-27 16:35 UTC, stratofax commented on erlenepsyd.com/content/blog/focus-on-curiosity.md
> +**Activities**
This should be an H2 heading, not bold:

```
## Activities
```

2022-09-27 16:35 UTC, stratofax commented on erlenepsyd.com/content/blog/focus-on-curiosity.md
> +In what way(s) has this interest/passion Transformed you as a person?
For the three preceeding paragraphs (or grafs for short):

- Remove 19th century capitalization (so, "growth" instead of "Growth"). If she wants to emphasize these terms, she should use bold, not Strange and Outmoded Forms of Capitalization.
- Turn this into a bullet list.
- Replace the slash with "or" -- so, "interest or passion "

2022-09-27 16:35 UTC, stratofax commented on erlenepsyd.com/content/blog/focus-on-curiosity.md
> +### **Something to Do**
Remove the bold (`**`) and keep the H3 (`###`)

2022-09-27 16:35 UTC, stratofax commented on erlenepsyd.com/content/blog/focus-on-curiosity.md
> +I have learned over time to rely on nature in simple, quiet ways in order to encourage openness and get unstuck when that is needed. Two old favorite activities of mine are to sit on a rock and to le
I'm not a big fan of her use of parenthesis, or Victorian Era Capitalizations. I'd rewrite the last sentence as follows:

```
I invite you to choose one and do it -- or do both if you can, and identify which you prefer.
```

2022-09-27 16:35 UTC, stratofax commented on erlenepsyd.com/content/blog/focus-on-curiosity.md
> +**Sitting on a Rock**
I think this should be an H4:

```
#### Sitting on a Rock
```

2022-09-27 16:35 UTC, stratofax commented on erlenepsyd.com/content/blog/focus-on-curiosity.md
> +**Leaning on a Tree**
Also H4

2022-09-27 16:35 UTC, stratofax commented on erlenepsyd.com/content/blog/focus-on-curiosity.md
> +And perhaps: "What would please me right now?"
Make these two grafs a bullet list

2022-09-27 16:35 UTC, stratofax commented on erlenepsyd.com/content/blog/focus-on-curiosity.md
> +3.  Follow up on one of your curiosity items. Use the computer (Good morning, Google). Use a dictionary (do you still have one?) Use a book to learn more. Make a phone call to someone who you think i
Rewrite as follows:

```
3.  Follow up on one of your curiosity items. 

Some ideas:  

- Use the computer. Good morning, Google! 
- Use a dictionary. Do you still have one? If not, try Google!
- Read a book to learn more. 
- Make a phone call to someone who you think is interested in that topic, maybe that person has some knowledge to share. Extra points for socialization here! 
- Find out if there are interest groups or activities in your community for your curiosity item. 
- If you have a creative bent, think about what piqued your curiosity and sketch it or play it to music ... or dance.
```

2022-09-27 16:35 UTC, stratofax commented on poetry.lock
> +version = "2.13.0"
Did you run `poetry update`? That will update the `poetry.lock` file. Try to avoid this if possible -- sometimes incrementing the versions can cause problems.

If you do update the poetry.lock file, just add it to a separate commit.

2022-09-27 16:42 UTC, flexicon33 commented on erlenepsyd.com/content/blog/focus-on-curiosity.md
> +![Boy filled with wonder]({static}/images/kyle-nieber-f0tKahz0DVA-unsplash.jpg){: .image-process-crisp}
Good suggestion, i'll make this change.

2022-09-27 16:44 UTC, flexicon33 commented on erlenepsyd.com/content/blog/focus-on-curiosity.md
> +Focus on: CURIOSITY
I'll remove the "focus on" line.
Regarding the "Thoughts and suggestions..." line, this has been on every blog post so far. Happy to remove it, but just confirm you still want me to?

2022-09-27 16:46 UTC, flexicon33 commented on erlenepsyd.com/content/blog/focus-on-curiosity.md
> +How is curiosity diminished?
ok

2022-09-27 16:49 UTC, flexicon33 commented on erlenepsyd.com/content/blog/focus-on-curiosity.md
> +A lot of time it is diminished by what we tell ourselves. Especially those recurring negatives and self-defeating 'over and over' ones. Some examples of things we tell ourselves: "What difference wou
will do

2022-09-27 16:49 UTC, flexicon33 commented on erlenepsyd.com/content/blog/focus-on-curiosity.md
> +"That's kind of different/neat/cool. I wonder..." "I have no idea how/about (something). I'm going to look it up." "The newspaper was reviewing a show at the (theatre/cinema/museum/etc.) I haven't be
ok

2022-09-27 16:50 UTC, flexicon33 commented on erlenepsyd.com/content/blog/focus-on-curiosity.md
> +Focus on: CURIOSITY
Actually I gather that your comment was only about the "focus on" line, but I was confused since for your comment, GitHub shows me this line and the prior 3 lines as well.

2022-09-27 18:01 UTC, flexicon33 commented on erlenepsyd.com/content/blog/focus-on-curiosity.md
> +3.  Follow up on one of your curiosity items. Use the computer (Good morning, Google). Use a dictionary (do you still have one?) Use a book to learn more. Make a phone call to someone who you think i
So there should be a space before an ellipsis? If so, should I change the others as well?

2022-10-03 21:37 UTC, stratofax commented on erlenepsyd.com/content/blog/focus-on-curiosity.md
> +3.  Follow up on one of your curiosity items. Use the computer (Good morning, Google). Use a dictionary (do you still have one?) Use a book to learn more. Make a phone call to someone who you think i
Either there's a space both before and after the ellipsis, or there's no space at all on either side. But no space on one side and a space on the other… no way!

(See what I did there… )

In all seriousness, adding a space on either side is preferred, to ensure optimal word wrapping.

I noticed that the site uses… Erlene-style ellipsis. I don't think this is the hill to die on, because the guidance around ellipsis are … contradictory: [punctuation - Spaces for Ellipses - English Language & Usage Stack Exchange](https://english.stackexchange.com/questions/115022/spaces-for-ellipses).

My rules:

* Use the Unicode single character ellipsis ( … ) whenever possible, instead of typing out three periods ( ... ). Note that typogrify conversions of Markdown will convert three-dot ellipsis into single character Unicode ellipsis.
* Always surround your ellipsis … with spaces!
* Unless you are "… starting a quote" or "ending a quote …"
* Don't worry about this too much since no one can agree.

2022-10-13 21:16 UTC, stratofax approved these changes

2022-10-13 21:17 UTC, merged